service: gwms-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  memorySize: 512
  versionFunctions: false
  stage: ${opt:stage, 'qa'}
  region: ${opt:region, 'us-east-1'}

  # you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "arn:aws:lambda:*:*:function:*"

  # you can define service wide environment variables here
  environment:
    MONGO_URI: ${env:MONGO_URI}


functions:
  GwmsApiGatewayProxy:
    handler: lambda.handler
    name: ${self:service}-ApiGatewayProxy-${opt:stage}
    description: "Api gateway proxy"
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
